### ISSUE TITLE
Cannot successfully use identify_tables(self)

### ISSUE THREAD

**Issue by russelau** [yannbanas/mrkdwn_analysis#1]
Amazing work you got here. 
I tried playing around with your mrkdwn_analysis, and somehow I can't make identify_tables() to work on my end. Am I using it wrong? See usage below.

**Sample Markdown file Used:**
```md
# Header 1

The intent of this file is to be read by `code.py`. 

## Header 2

This part will have tables which should be analyzed using the function `analyze_tables()`

| Sample | Sample2 |
| :------: | :------- |
| Data1 | row1-col2 |
```

**Code:**
```py
from mrkdwn_analysis import MarkdownAnalyzer

analyzer = MarkdownAnalyzer(".\\README.md")

headers = analyzer.identify_headers()
sections = analyzer.identify_sections()
tables = analyzer.identify_tables()
wordCount = analyzer.count_words()

print(headers)
print(sections)
print(wordCount)
print(tables)
```

**Output:**
```log
PS > py .\code.py
{'Header': ['Header 1', 'Header 2']}
{}
47
{}
```

**Comment by yannbanas** [comment]
Hello
thank you for using my first package
I've uploaded a temporary solution you can use to retrieve it.
pip install markdown-analysis==0.0.5
keep your code as before and it should work

**Comment by russelau** [comment]
Thank you so much! I was able to get data from the table now. I also tried using a much more complex markdown file and was able to confirm that `identify_tables()` works great! 

This project is great. Keep up the good work!
