### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 72: invalid start byte

### ISSUE THREAD

**Issue by markwkiehl** [yannbanas/mrkdwn_analysis#3]
Cannot use MarkdownAnalyzer on Windows OS system.

from pathlib import Path

# pip install markdown-analysis
# https://github.com/yannbanas/mrkdwn_analysis
from mrkdwn_analysis import MarkdownAnalyzer

path_file_pdf = Path(Path.cwd().parent).joinpath("data/pdf_conv_test_1.pdf")        # utf-8

md_anal = MarkdownAnalyzer(path_file_pdf, encoding="utf-8")

headers = md_anal.identify_code_blocks()
print(headers)

Output:

  File "c:\Users\Mark Kiehl\Documents\computer\Python\venv\api\lib\site-packages\mrkdwn_analysis\markdown_analyzer.py", line 8, in __init__
    self.lines = file.readlines()
  File "C:\Users\Mark Kiehl\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 72: invalid start byte

**Comment by yannbanas** [comment]
As mentioned in the email, this script only works with .md files, not .pdf. A new version (0.1.0) has been released with numerous improvements and fixes. Thank you for testing it and keeping me informed. If you still encounter any issues, please provide the example code and the problematic document so I can see what I can do.
